services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/code
    depends_on:
      - pgdb
    ports:
      - 8010:8000
    entrypoint: sh /code/entrypoint.sh

  pgdb:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5442:5432
    env_file:
      - .env

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   entrypoint: redis-server --appendonly yes
  #   # ports:
  #   #   - 6379:6379
  #   volumes:
  #     - ./redis_data:/var/lib/redis
  #     - ./redis/rc.local:/etc/rc.local
